### ISSUE TITLE
Use HOPE to calculate NoP_0 and NoP_1

### ISSUE THREAD

**Issue by jvarnon1** [jvarnon1/ECE459PUF-Maker#2]
To compute Fault Impact we need to compute from a set of test patterns:

The number of patterns that detect the s-a-0 fault (NoP_0)
The number of patterns that detect the s-a-1 fault (NoP_0)

At each node.

**Comment by GrahamW4** [comment]
[20210316_OnBoardNotes_annotated.pdf](https://github.com/jvarnon1/ECE459PUF-Maker/files/6224012/20210316_OnBoardNotes_annotated.pdf)

**Comment by GrahamW4** [comment]
Pages 3-6 explain how to do testing for stuck at fault model. Its pretty simple and probably should not be too bad to code. The gates with the highest testability rate which is the average testability between S@1 and S@0, are the ones most considered for XOR or MUX gate. We can also test controllability which is also referenced in the notes.

**Comment by jvarnon1** [comment]
@GrahamW4 rather than write code, I have figured out how to use HOPE to calculate Fault Impact. The Excel file contains the results. The other files are hope generated which I used to get the info.
